### ISSUE TITLE
withScope is marked as optional, but is required

### ISSUE THREAD

**Issue by cappslock** [BrunoScheufler/graphql-middleware-sentry#134]
In the README, it looks like `withScope` is marked as not required, but an error is thrown if you don't provide it. Looking at the code, it definitely seems to be required: https://github.com/BrunoScheufler/graphql-middleware-sentry/blob/master/src/index.ts#L75

Any reason it couldn't be defaulted to the identity function? If so I'd be happy to make a PR.

**Comment by BrunoScheufler** [comment]
Thanks for adding the default 🙌 I'll make sure to release this as soon as possible 👍
