### ISSUE TITLE
context.authorization.userId is not defined.

### ISSUE THREAD

**Issue by coreysnyder** [BrunoScheufler/graphql-middleware-sentry#236]
I tried running your example and noticed I don't have a `context.authorization` defined like the example has here:
```javascript
scope.setUser({
      id: context.authorization.userId,
    });
```

Are there any best practices or guides on setting up your app so this data is available. The only thing I pass in the headers is an `authorization` string set to `Bearer k23lkjfwfjo3...`

Should I have the front-end tack on a bunch of extra headers for info that I might want in the logs? And then read them like so:
```javascript
scope.setUser({
      user_id: context.request.headers['user_id'],
      user_email: context.request.headers['user_email'],
      user_token: context.request.headers['user_token'],
      user_role: context.request.headers['user_role'],
      user_name: context.request.headers['user_name'],
    })
```

**Comment by BrunoScheufler** [comment]
Hey! This will depend on the underlying server, as you'll be able to customize which information gets added to the context once a request comes in. And by that, everything added to the Context can be used 👍
