### ISSUE TITLE
Async withScope

### ISSUE THREAD

**Issue by nickluger** [BrunoScheufler/graphql-middleware-sentry#38]
### Feature request: Async `withScope`
```js
withScope: async (scope, error, ctx) => {
``` 

`withScope` function could be awaited,
```js
await withScope(scope, err, ctx)
```

and then of course
```js
await captureException(res, ctx, withScope)
```

This way we could, for example, fetch a user on demand using:
```js
const currentUser = await ctx.db.get(...);
if(currentUser) {
  scope.setUser(currentUser)
}
```
or similar

**Comment by BrunoScheufler** [comment]
@nickluger thanks for this idea, using withScope in an async manner would really make things easier, I agree! Will look after your PR shortly 👍

**Comment by BrunoScheufler** [comment]
@nickluger just realized that you didn't submit a PR for this suggestion, would you like to work on this?

**Comment by nickluger** [comment]
Seems like this is an issue at Sentry's repo, as `withScope` is not async/cannot be awaited.

https://forum.sentry.io/t/nested-withscope-with-async-functions/5433/2

https://github.com/getsentry/sentry-docs/issues/939

I'll close it here.
