### ISSUE TITLE
Error: Missing the sentryInstance or the dsn parameter in configuration.

### ISSUE THREAD

**Issue by schatzdesigns** [BrunoScheufler/graphql-middleware-sentry#60]
I get this error:

Error: Missing the sentryInstance or the dsn parameter in configuration.

When I user the middleware with the new Apollo-Server v2.

How do we set up the middleware with Apollo-Server v2?

Here's the initialization code:

![image](https://user-images.githubusercontent.com/3469965/58172665-d49abb80-7ca1-11e9-8082-5854a2f7f96b.png)

**Comment by BrunoScheufler** [comment]
@schatzdesigns hey there 👋 Sorry for getting back this late, do you maybe have more context to this, for example the code where you initialize the Apollo Server instance? If so, it would be great to have that at hand 👍 From what you wrote, it rather sounds like you're not passing in either an existing sentry instance or a DSN to build a new instance from 🤔

**Comment by bukhalo** [comment]
Same error:

Init sentry in separate `lib/sentry.js` file
```javascript
import * as Sentry from '@sentry/node';
import { version } from '../../package';

const sentryInstance = Sentry.init({
  dsn: `https://${process.env.SENTRY_KEY}@sentry.io/${
    process.env.SENTRY_PROJECT_ID
  }`,
  version,
  environment: process.env.NODE_ENV,
});

export default sentryInstance;
```

Import sentry instance to sentry graphql middlware 
```javascript
import Sentry from 'lib/sentry';
import { sentry } from 'graphql-middleware-sentry';

const sentryMiddleware = sentry({
  sentryInstance: Sentry,
  withScope: (scope, error, context) => {
    console.log(context);
    scope.setUser({
      id: context.authorization.userId,
    });
    scope.setExtra('body', context.request.body);
    scope.setExtra('origin', context.request.headers.origin);
    scope.setExtra('user-agent', context.request.headers['user-agent']);
  },
});

export default sentryMiddleware;
```

Output
```
Error: Missing the sentryInstance or the dsn parameter in configuration.
    at new SentryError (/Users/***/Projects/***/api/node_modules/graphql-middleware-sentry/dist/index.js:56:42)
    at exports.sentry (/Users/***/Projects/***/api/node_modules/graphql-middleware-sentry/dist/index.js:65:15)
    at Object.<anonymous> (/Users/***/Projects/***/api/src/middleware/graphql/sentry.js:4:62)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Module._compile (/Users/***/Projects/***/api/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Object.newLoader [as .js] (/Users/***/Projects/***/api/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by BrunoScheufler** [comment]
@bukhalo interesting! What happens if you build the sentryMiddleware in a method (like a factory) or at the place you use it in? Currently it looks to me as if the way you have the middleware & instance separated and initialized from the beginning makes it not work because some reason. I'd be interested in how it behaves when you create the sentry & middleware instance in a function which is called when the app starts up
