### ISSUE TITLE
Looking to grab the event id from sentryInstance.captureException

### ISSUE THREAD

**Issue by ryankauk** [BrunoScheufler/graphql-middleware-sentry#99]
Hey, this middleware made it really easy for me, they only thing is that I'm looking to get the eventId to attach to the forwarded error and pass to the client.

**Comment by ryankauk** [comment]
Added a pull request for this https://github.com/BrunoScheufler/graphql-middleware-sentry/pull/100

**Comment by BrunoScheufler** [comment]
@ryankauk hey! Sorry for getting back to you this late, I'll immediately have a look at your PR 👍
